### ISSUE TITLE
No me muestra información

### ISSUE THREAD

**Issue by Alcor17** [jaumebosch/MMM-TMB#3]
Hola Jaume.

Instalé tu módulo (hoy lo actualicé) en una Raspberry Pi 3B+ con Magic Mirror actualizado a la última versión y como SO Raspbian, pero no he logrado que se visualice en el módulo información alguna. Me registré en la web de TMB para obtener la appKey, la appID y pusé el código de la parada a visualizar, pero como digo, no obtengo ningún  resultado. ¿Podrías ayudarme a encontrar el por qué no se muestra la información?

Gracias y un saludo.

**Comment by jaumebosch** [comment]
Has ejecutado el npm install dentro del directorio? es necesario el paquete "moment" para poder mostrar bien los tiempos.
También he añadido el paquete "request" por si acaso

**Comment by jaumebosch** [comment]
te adjunto un ejemplo de la configuración
 {
            module: 'MMM-TMB',
            position: "bottom_right",   // This can be any of the regions.
            config: {
            	appId: 'XXXXXXX',
            	appKey: 'XXXXXXXXXXXXXXXXXXXX',
            	busStopCode: 389,
            	refreshInterval: 5000
            }
        }

**Comment by Alcor17** [comment]
Hola Jaume.
Gracias por tus respuestas.
Cuando actualicé lo hice desde la carpeta del modulo con "git pull" y luego "npm install ". No tengo instalado moment, desde donde puedo descargarlo?
De todas maneras he seguido tu ejemplo  de  configuración y en el busStopCode he quitado los 00 de la izquierda del código de parada (creí que había  que ponerlos también tal y como lo muestra TMB) y ya está mostrándome los datos.

**Comment by jaumebosch** [comment]
genial!
El "moment" se te debería instalar al hacer "npm install" dentro del directorio /MMM-TMB

Saludos!

P.D. Se aceptan "stars" :D
