### ISSUE TITLE
No es pot obtindre informació

### ISSUE THREAD

**Issue by adocampo** [jaumebosch/MMM-TMB#4]
Abans de res, merci per aquest mòdul, el trobo súper útil i una bona excusa per donar-li un cop d'ull al mirall abans de sortir de casa ;)

Suposo que més que un bug, ha de ser alguna configuració dolenta. Però no veig on estic fallant.

Primer de tot, vaig crear-ne un compte a https://developer.tmb.cat i vaig enregistrar una nova aplicació, amb aquests paràmentres:
![image](https://user-images.githubusercontent.com/2266612/93486182-3013a280-f904-11ea-89a7-db8c4f2a0992.png)

Després, he instal·lat el mòdul (amb mmpm) i a dins de `config.js` he posat aquesta configuració dins de l'array de mòduls:
```
      {
            module: 'MMM-TMB',
            position: "bottom_right",   // This can be any of the regions.
            config: {
                appId: "92e75XXX",
                appKey: "cb9a2ce58b9acc1eca6353dc3XXXXXXX",
                busStopCode: "000804",
                busLine: "D40"
            }
        },
```
Com pots veure, el codi de parada 000804 té el bus D40
![image](https://user-images.githubusercontent.com/2266612/93486987-1c1c7080-f905-11ea-8848-1f84c79e417b.png)

Però sempre diu això
![image](https://user-images.githubusercontent.com/2266612/93486701-c9db4f80-f904-11ea-9e31-9bc35e58a225.png)

Veig que els paràmetres són strings, per això poso entre cometes dobles els valors...

Veus on l'estic cagant?

Merci!!

**Comment by jaumebosch** [comment]
Bones, he estat fent probes i he trobat el problema.
Tan sols has de posar el codi de la parada sense els zeros del devant, es a di "804". Ara faré una modificació al codi per a que tregui els _leading _zeros__

Gràcies!

**Comment by adocampo** [comment]
Efectivament, treient els _leading zeros_ funciona a la perfecció!

Moltes gràcies!
