### ISSUE TITLE
Filtre de línia mostra "undefined" com a nom

### ISSUE THREAD

**Issue by adocampo** [jaumebosch/MMM-TMB#5]
**Describe the bug**
Quan es filtra una parada amb nom de la línia, funciona, però en lloc de posar el nom de la línia, mostra "undefined".

**To Reproduce**
1. edita `config.json`
2. configura MMM-TMB amb el paràmetre
```
 busLine: "D40"
```

**Expected behavior**
Hauria de mostrar el nom de la línia de bus, en lloc de undefined

**Screenshots**

![image](https://user-images.githubusercontent.com/2266612/94362549-64cde980-00bc-11eb-8e69-c6c592eeca95.png)
![image](https://user-images.githubusercontent.com/2266612/94362560-77e0b980-00bc-11eb-860c-4d5a74dce913.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Qualsevol

**Comment by jaumebosch** [comment]
Solved, TMB ha canviat l'estructura de la resposta quan només demanes per una linea :/
