### ISSUE TITLE
Múltiples parades

### ISSUE THREAD

**Issue by adocampo** [jaumebosch/MMM-TMB#8]
Seria bo poder posar més d'una parada de bus a la configuració. Així abans de sortir de casa pots decidir si vas a una parada o l'altra, si tens més d'una a prop de casa.
Alguna cosa que es pogués configurar amb un array dels paràmetres com ara `busStopCode` o `busLine` com per exemple
```
                {
                    module: 'MMM-TMB',
                    position: "bottom_right",   // This can be any of the regions.
                    config: {
                        appId: "92e7XXXX",
                        appKey: "cb9a2ce58b9acc1eca6353dc3dXXXXXX",
                        busStops: [
                                           { 
                                             busStopCode: "804", 
                                             busLine: "D40",
                                             maxEntries: 4
                                            }
                                            { 
                                             busStopCode: "189", 
                                             busLine: "60",
                                             refreshInterval: 20000
                                            }
                        ]
                }
                }
```
EDITAT: A més, si hi ha més d'una parada, també es podria posar el nom de la parada amb `busStopName`

Què n'opines?

**Comment by jaumebosch** [comment]
hi ha una branch que es aquesta funcionalitat, pero encara WiP 😄

**Comment by adocampo** [comment]
Oh, guai, per què he provat d'inserir dos mòduls MMM-TMB amb informació de dues parades, però 1) em surt el header TMB iBUS per duplicat, ocupant espai, i 2) la informació del segon mòdul sobreescriu al primer (és a dir, que si tinc configurades la parada A i la B, surten dos mòduls amb la informació de la parada B).

Em quedo per aquí a veure si la branch aquesta veu la llum algún día :grimacing:

**Comment by jaumebosch** [comment]
Segur que si!

**Comment by jaumebosch** [comment]
Done, 
take in consideration new config.js structure has breaking changes and remember to execute npm install in order to install new dependencies (axios)

**Comment by jaumebosch** [comment]
Follows and Stars accepted 😄
